### ISSUE TITLE
Trouble, maybe python 3.6?

### ISSUE THREAD

**Issue by sj26** [cyanogen/uchroma#23]
I'm having a little trouble with uchroma from AUR on Arch. I had to do some `udevadm control --reload` and `udevadm trigger` shenanigans before the hid devices could find their udev parent hidraw cousins. Maybe this should go in the AUR package?

Anyways, now I'm here:

```
[sj26@wheeljack ~]$ uchromad --debug
 uchroma.driver-0/DEBUG    | Loaded renderers: uchroma.fxlib.plasma.Plasma, uchroma.fxlib.rainbow.Rainbow, uchroma.fxlib.ripple.Ripple
 uchroma.driver-1/DEBUG    | Loaded renderers: uchroma.fxlib.plasma.Plasma, uchroma.fxlib.rainbow.Rainbow, uchroma.fxlib.ripple.Ripple
 uchroma.devicemanager/DEBUG    | Udev monitor started
 uchroma.power/INFO     | Connected screensaver: org.freedesktop.ScreenSaver (':1.41',)
 uchroma.power/INFO     | Connected screensaver: org.gnome.ScreenSaver (':1.16',)
 uchroma.power/INFO     | Connected to org.freedesktop.login1 (':1.1',)
 uchroma.server/INFO     | add: UChromaWirelessMouse(name=Mamba (Wireless), type=Mouse, product_id=0x0045, index=0)
 uchroma.server/INFO     | add: UChromaKeyboard(name=Ornata Chroma, type=Keyboard, product_id=0x021e, index=1)
Unhandled exception in async future
future: <Task finished coro=<UChromaDeviceManager._fire_callbacks() done, defined at /usr/lib/python3.6/site-packages/uchroma/server/device_manager.py:90> exception=TypeError('only integer scalar arrays can be converted to a scalar index',) created at /usr/lib/python3.6/site-packages/uchroma/util.py:278>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_manager.py", line 96, in _fire_callbacks
    yield from callback(action, device)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 736, in _dm_callback
    path = self._publish_device(device)
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 712, in _publish_device
    devapi = DeviceAPI(device, self._bus)
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 113, in __init__
    self.__class__.dbus = self._get_descriptor()
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 301, in _get_descriptor
    if hasattr(self._driver, name):
  File "/usr/lib/python3.6/site-packages/uchroma/server/mouse.py", line 183, in battery_level
    value = self.run_with_result(UChromaWirelessMouse.Command.GET_BATTERY_LEVEL)
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 341, in run_with_result
    result = report.result
  File "/usr/lib/python3.6/site-packages/uchroma/server/report.py", line 201, in result
    return bytes(self._result)
TypeError: only integer scalar arrays can be converted to a scalar index
Unhandled exception in async future
future: <Task finished coro=<UChromaDeviceManager._fire_callbacks() done, defined at /usr/lib/python3.6/site-packages/uchroma/server/device_manager.py:90> exception=TypeError('only integer scalar arrays can be converted to a scalar index',) created at /usr/lib/python3.6/site-packages/uchroma/util.py:278>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_manager.py", line 96, in _fire_callbacks
    yield from callback(action, device)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 736, in _dm_callback
    path = self._publish_device(device)
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 712, in _publish_device
    devapi = DeviceAPI(device, self._bus)
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 113, in __init__
    self.__class__.dbus = self._get_descriptor()
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 301, in _get_descriptor
    if hasattr(self._driver, name):
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 435, in firmware_version
    version = self._get_firmware_version()
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 426, in _get_firmware_version
    return self.run_with_result(BaseUChromaDevice.Command.GET_FIRMWARE_VERSION)
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 341, in run_with_result
    result = report.result
  File "/usr/lib/python3.6/site-packages/uchroma/server/report.py", line 201, in result
    return bytes(self._result)
TypeError: only integer scalar arrays can be converted to a scalar index
```

Kinda looks like the Ornata and Mamba might be doing something unexpected?

The server keeps running, but the client doesn't seem to see anything:

```
[sj26@wheeljack ~]$ uchroma
usage: uchroma [-v] [-g] [-d DEVICE] [-l] {} ...
uchroma: error: Multiple devices found, select one with --device
[sj26@wheeljack ~]$ uchroma -v
uchroma-1.0
[sj26@wheeljack ~]$ uchroma -l
[sj26@wheeljack ~]$ uchroma -d 0 
usage: uchroma [-v] [-g] [-d DEVICE] [-l] {} ...
uchroma: error: Invalid device: 0
[sj26@wheeljack ~]$ uchroma -d 1
usage: uchroma [-v] [-g] [-d DEVICE] [-l] {} ...
uchroma: error: Invalid device: 1
```

**Comment by sj26** [comment]
I think this might be Python 3.6 trouble? I just updated server/report.py to remove the `bytes(...)` around `self._result` and now I can see a battery level!

```
[sj26@wheeljack ~]$ python
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uchroma.server.device_manager
>>> uchroma.server.device_manager.UChromaDeviceManager().devices
OrderedDict([('1532:0045.00', UChromaWirelessMouse(name=Mamba (Wireless), type=Mouse, product_id=0x0045, index=0)), ('1532:021e.01', UChromaKeyboard(name=Ornata Chroma, type=Keyboard, product_id=0x021e, index=1))])
>>> uchroma.server.device_manager.UChromaDeviceManager().devices['1532:0045.00']
UChromaWirelessMouse(name=Mamba (Wireless), type=Mouse, product_id=0x0045, index=0)
>>> uchroma.server.device_manager.UChromaDeviceManager().devices['1532:0045.00'].battery_level
58.82352941176471
```

But the server still is unhappy:

```
uchromad --debug
 uchroma.driver-0/DEBUG    | Loaded renderers: uchroma.fxlib.plasma.Plasma, uchroma.fxlib.rainbow.Rainbow, uchroma.fxlib.ripple.Ripple
 uchroma.driver-1/DEBUG    | Loaded renderers: uchroma.fxlib.plasma.Plasma, uchroma.fxlib.rainbow.Rainbow, uchroma.fxlib.ripple.Ripple
 uchroma.devicemanager/DEBUG    | Udev monitor started
 uchroma.power/INFO     | Connected screensaver: org.freedesktop.ScreenSaver (':1.41',)
 uchroma.power/INFO     | Connected screensaver: org.gnome.ScreenSaver (':1.16',)
 uchroma.power/INFO     | Connected to org.freedesktop.login1 (':1.1',)
 uchroma.server/INFO     | add: UChromaWirelessMouse(name=Mamba (Wireless), type=Mouse, product_id=0x0045, index=0)
 uchroma.driver-0/DEBUG    | Device API attached: <node>
  <interface name='org.chemlab.UChroma.Device'>
    <property name='BatteryLevel' type='d' access='read' />
    <property name='DeviceIndex' type='u' access='read' />
    <property name='DeviceType' type='s' access='read' />
    <property name='DriverVersion' type='s' access='read' />
    <property name='HasMatrix' type='b' access='read' />
    <property name='Height' type='i' access='read' />
    <property name='IsCharging' type='b' access='read' />
    <property name='IsWireless' type='b' access='read' />
    <property name='Key' type='s' access='read' />
    <property name='Manufacturer' type='s' access='read' />
    <property name='Name' type='s' access='read' />
    <property name='ProductId' type='u' access='read' />
    <property name='KeyMapping' type='a{saau}' access='read' />
    <property name='SysPath' type='s' access='read' />
    <property name='VendorId' type='u' access='read' />
    <property name='Width' type='i' access='read' />
    <property name='PollingRate' type='s' access='readwrite'>
      <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='true' />
    </property>
    <property name='Brightness' type='d' access='readwrite'>
      <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='true' />
    </property>
    <property name='Suspended' type='b' access='readwrite'>
      <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='true' />
    </property>
    <method name='Reset' />
  </interface>
</node>
 uchroma.server/INFO     | add: UChromaKeyboard(name=Ornata Chroma, type=Keyboard, product_id=0x021e, index=1)
 uchroma.driver-1/ERROR    | Got error UNSUPPORTED for command 03,81
 uchroma.driver-1/ERROR    | Command failed with status UNSUPPORTED
 uchroma.driver-1/ERROR    | Got error UNSUPPORTED for command 03,82
 uchroma.driver-1/ERROR    | Command failed with status UNSUPPORTED
 uchroma.driver-1/ERROR    | Got error UNSUPPORTED for command 03,83
 uchroma.driver-1/ERROR    | Command failed with status UNSUPPORTED
 uchroma.driver-1/DEBUG    | Device API attached: <node>
  <interface name='org.chemlab.UChroma.Device'>
    <property name='DeviceIndex' type='u' access='read' />
    <property name='DeviceType' type='s' access='read' />
    <property name='DriverVersion' type='s' access='read' />
    <property name='FirmwareVersion' type='s' access='read' />
    <property name='HasMatrix' type='b' access='read' />
    <property name='Height' type='i' access='read' />
    <property name='Key' type='s' access='read' />
    <property name='Manufacturer' type='s' access='read' />
    <property name='Name' type='s' access='read' />
    <property name='ProductId' type='u' access='read' />
    <property name='KeyMapping' type='a{saau}' access='read' />
    <property name='SysPath' type='s' access='read' />
    <property name='VendorId' type='u' access='read' />
    <property name='Width' type='i' access='read' />
    <property name='Brightness' type='d' access='readwrite'>
      <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='true' />
    </property>
    <property name='Suspended' type='b' access='readwrite'>
      <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='true' />
    </property>
    <method name='Reset' />
  </interface>
</node>
Unhandled exception in async future
future: <Task finished coro=<UChromaDeviceManager._fire_callbacks() done, defined at /usr/lib/python3.6/site-packages/uchroma/server/device_manager.py:90> exception=AttributeError("'UChromaWirelessMouse' object has no attribute '_close'",) created at /usr/lib/python3.6/site-packages/uchroma/util.py:278>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_manager.py", line 96, in _fire_callbacks
    yield from callback(action, device)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 737, in _dm_callback
    device.restore_prefs()
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 602, in restore_prefs
    with self.preferences.observers_paused():
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 587, in preferences
    self._prefs = PreferenceManager().get(self.serial_number)
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 414, in serial_number
    serial = self._get_serial_number()
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 400, in _get_serial_number
    value = self.run_with_result(BaseUChromaDevice.Command.GET_SERIAL)
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 340, in run_with_result
    if self.run_report(report, delay=delay):
  File "/usr/lib/python3.6/site-packages/wrapt/decorators.py", line 500, in _synchronized_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 356, in run_report
    return report.run(delay=delay, timeout_cb=self._get_timeout_cb())
  File "/usr/lib/python3.6/site-packages/uchroma/server/report.py", line 153, in run
    timeout_cb(self.status, None)
  File "/usr/lib/python3.6/site-packages/uchroma/server/mouse.py", line 158, in _timeout_cb
    self._close(True)
AttributeError: 'UChromaWirelessMouse' object has no attribute '_close'
Unhandled exception in async future
future: <Task finished coro=<UChromaDeviceManager._fire_callbacks() done, defined at /usr/lib/python3.6/site-packages/uchroma/server/device_manager.py:90> exception=AttributeError("'numpy.ndarray' object has no attribute 'decode'",) created at /usr/lib/python3.6/site-packages/uchroma/util.py:278>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_manager.py", line 96, in _fire_callbacks
    yield from callback(action, device)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/usr/lib/python3.6/site-packages/uchroma/server/dbus.py", line 737, in _dm_callback
    device.restore_prefs()
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 602, in restore_prefs
    with self.preferences.observers_paused():
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 587, in preferences
    self._prefs = PreferenceManager().get(self.serial_number)
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 414, in serial_number
    serial = self._get_serial_number()
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 401, in _get_serial_number
    return self._decode_serial(value)
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_base.py", line 386, in _decode_serial
    return value.decode()
AttributeError: 'numpy.ndarray' object has no attribute 'decode'
```

and asking for a list of devices now throws an exception:

```
[sj26@wheeljack ~]$ uchroma -l
Traceback (most recent call last):
  File "/usr/bin/uchroma", line 11, in <module>
    load_entry_point('uchroma==1.0', 'console_scripts', 'uchroma')()
  File "/usr/lib/python3.6/site-packages/uchroma/client/client.py", line 702, in run_client
    UChromaTool().run()
  File "/usr/lib/python3.6/site-packages/uchroma/client/cmd.py", line 40, in __init__
    self._list_devices(self._args)
  File "/usr/lib/python3.6/site-packages/uchroma/client/cmd.py", line 61, in _list_devices
    serial_number = dev.SerialNumber
AttributeError: '<CompositeObject>' object has no attribute 'SerialNumber'
```

**Comment by sj26** [comment]
Omg, seems it's my fault. I see you've [fixed this already](https://github.com/cyanogen/uchroma/blob/master/uchroma/server/report.py#L201), and the AUR is just lagging. I updated and all is well.

Thanks for making an awesome tool!
