### ISSUE TITLE
Manjaro install failed

### ISSUE THREAD

**Issue by PipeItToDevNull** [cyanogen/uchroma#25]
I am unsure how this is done, delete this if it is done incorrectly.

I cloned the repo and ran `sudo make install`

```
python3 setup.py install --root=/
running install
running build
running build_py
running egg_info
writing uchroma.egg-info/PKG-INFO
writing dependency_links to uchroma.egg-info/dependency_links.txt
writing entry points to uchroma.egg-info/entry_points.txt
writing requirements to uchroma.egg-info/requires.txt
writing top-level names to uchroma.egg-info/top_level.txt
reading manifest file 'uchroma.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'uchroma.egg-info/SOURCES.txt'
running build_ext
running install_lib
running install_egg_info
removing '/usr/lib/python3.6/site-packages/uchroma-1.0.1-py3.6.egg-info' (and everything under it)
Copying uchroma.egg-info to /usr/lib/python3.6/site-packages/uchroma-1.0.1-py3.6.egg-info
running install_scripts
Installing uchroma script to /usr/bin
Installing uchromad script to /usr/bin
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'platform'
  warnings.warn(msg)
python3 setup.py build_ext --inplace
running build_ext
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'platform'
  warnings.warn(msg)
install -m 644 -v -D install/70-uchroma.rules //etc/udev/rules.d/70-uchroma.rules
removed '//etc/udev/rules.d/70-uchroma.rules'
'install/70-uchroma.rules' -> '//etc/udev/rules.d/70-uchroma.rules'
python3 setup.py -q hwdb > /tmp/tmp.Yxjs0l1Moo
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'platform'
  warnings.warn(msg)
Traceback (most recent call last):
  File "/usr/lib/python3.6/pydoc.py", line 343, in safeimport
    module = __import__(path)
  File "/home/piper/Cloud/Documents/Config/bin/uchroma/uchroma/server/__init__.py", line 1, in <module>
    from .device import UChromaDevice
  File "/home/piper/Cloud/Documents/Config/bin/uchroma/uchroma/server/device.py", line 1, in <module>
    import hidapi
ModuleNotFoundError: No module named 'hidapi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    'Topic :: System :: Hardware :: Hardware Drivers'
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 51, in run
    print(HWDBGenerator.generate())
  File "setup.py", line 37, in generate
    hw = locate('uchroma.server.Hardware')
  File "/usr/lib/python3.6/pydoc.py", line 1581, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/usr/lib/python3.6/pydoc.py", line 358, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in uchroma.server - ModuleNotFoundError: No module named 'hidapi'
make: *** [Makefile:20: install_udev] Error 1
 
```

**Comment by cyanogen** [comment]
Are you able to "import hidapi" from a Python shell?

What *should* be happening is:

1. Dependencies get installed
2. Native bits are compiled
3. Python code is installed w/ compiled native libs
4. hwdb target is run to dump out all info for supported devices so udev can tag them

**Comment by z3ntu** [comment]
@PipeItToDevNull You can use the AUR package (see the readme) on Manjaro.

**Comment by PipeItToDevNull** [comment]
@z3ntu The AUR package does not build either, that is why I tried the make file

@cyanogen I am attempting to figure out what exactly that means. 

I have run `pip install hidapi` and `pip install hidapi-cffi` 

After installing the second my error changes to:
```

┌─[29]─[piper@ENCOMcorp]─[~/.bin/uchroma]
└╼ sudo make install
python3 setup.py install --root=/
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'platform'
  warnings.warn(msg)
running install
running build
running build_py
running egg_info
writing uchroma.egg-info/PKG-INFO
writing dependency_links to uchroma.egg-info/dependency_links.txt
writing entry points to uchroma.egg-info/entry_points.txt
writing requirements to uchroma.egg-info/requires.txt
writing top-level names to uchroma.egg-info/top_level.txt
reading manifest file 'uchroma.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'uchroma.egg-info/SOURCES.txt'
running build_ext
running install_lib
running install_egg_info
removing '/usr/lib/python3.6/site-packages/uchroma-1.0.1-py3.6.egg-info' (and everything under it)
Copying uchroma.egg-info to /usr/lib/python3.6/site-packages/uchroma-1.0.1-py3.6.egg-info
running install_scripts
Installing uchroma script to /usr/bin
Installing uchromad script to /usr/bin
python3 setup.py build_ext --inplace
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'platform'
  warnings.warn(msg)
running build_ext
install -m 644 -v -D install/70-uchroma.rules //etc/udev/rules.d/70-uchroma.rules
removed '//etc/udev/rules.d/70-uchroma.rules'
'install/70-uchroma.rules' -> '//etc/udev/rules.d/70-uchroma.rules'
python3 setup.py -q hwdb > /tmp/tmp.bak3RytgcN
/usr/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'platform'
  warnings.warn(msg)
Traceback (most recent call last):
  File "/usr/lib/python3.6/pydoc.py", line 343, in safeimport
    module = __import__(path)
  File "/home/piper/Cloud/Documents/Config/bin/uchroma/uchroma/server/__init__.py", line 1, in <module>
    from .device import UChromaDevice
  File "/home/piper/Cloud/Documents/Config/bin/uchroma/uchroma/server/device.py", line 1, in <module>
    import hidapi
  File "/usr/lib/python3.6/site-packages/hidapi.py", line 59, in <module>
    raise OSError("Could not find any hidapi library")
OSError: Could not find any hidapi library

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    'Topic :: System :: Hardware :: Hardware Drivers'
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 51, in run
    print(HWDBGenerator.generate())
  File "setup.py", line 37, in generate
    hw = locate('uchroma.server.Hardware')
  File "/usr/lib/python3.6/pydoc.py", line 1581, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/usr/lib/python3.6/pydoc.py", line 358, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in uchroma.server - OSError: Could not find any hidapi library
make: *** [Makefile:20: install_udev] Error 1

```

I googled about importing and added both packages to the top import area of `setup.py` but installation is not made any better by that

**Comment by z3ntu** [comment]
@PipeItToDevNull Could you please give me the full error message of the AUR build? Then I can at least try to help you further.

**Comment by PipeItToDevNull** [comment]
```
┌─[37]─[piper@ENCOMcorp]─[~/.bin/uchroma]
└╼ yaourt -S uchroma

==> Downloading uchroma PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
x uchroma.install
uchroma 1.0.1-1  (2017-03-19 20:07)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> uchroma dependencies:
 - python (already installed)
 - python-wrapt (package found)
 - python-traitlets (package found)
 - python-ruamel-yaml (package found)
 - python-scikit-image (building from AUR)
 - python-pydbus (building from AUR)
 - python-hsluv (building from AUR)
 - python-hidapi-cffi (building from AUR)
 - python-frozendict (package found)
 - python-colorlog (building from AUR)
 - python-argcomplete (building from AUR)
 - python-grapefruit (building from AUR)
 - python-cffi (package found)
 - hidapi (package found)
 - python-evdev (building from AUR)
 - python-pyudev (package found)
 - python-hidapi (package found)
 - python-gbulb (building from AUR)
 - python-colr (building from AUR)
 - python-dask (building from AUR)
 - cython (package found) [makedepend]
 - python-pytest-runner (package found) [makedepend]


==> Edit uchroma.install ? [Y/n] ("A" to abort)
==> -------------------------------------------
==> n

==> Continue building uchroma ? [Y/n]
==> ---------------------------------
==> y

==> Building and installing package
==> Install or build missing dependencies for uchroma:
[sudo] password for piper: 
resolving dependencies...
looking for conflicting packages...

Packages (15) python-decorator-4.0.11-1  python-ply-3.10-1  python-py-1.4.32-2  python-pycparser-2.17-2  python-pytest-3.0.6-1  cython-0.25.2-2  hidapi-0.8.0rc1-2  python-cffi-1.9.1-2  python-frozendict-1.2-2  python-hidapi-0.7.99.20-1
              python-pytest-runner-2.11.1-1  python-pyudev-0.21.0-2  python-ruamel-yaml-0.13.14-1  python-traitlets-4.3.2-1  python-wrapt-1.10.8-2

Total Installed Size:  16.84 MiB

:: Proceed with installation? [Y/n] y
(15/15) checking keys in keyring                                                                                                                        [----------------------------------------------------------------------------------------------] 100%
(15/15) checking package integrity                                                                                                                      [----------------------------------------------------------------------------------------------] 100%
(15/15) loading package files                                                                                                                           [----------------------------------------------------------------------------------------------] 100%
(15/15) checking for file conflicts                                                                                                                     [----------------------------------------------------------------------------------------------] 100%
error: failed to commit transaction (conflicting files)
python-pycparser: /usr/lib/python3.6/site-packages/pycparser-2.17-py3.6.egg-info/PKG-INFO exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser-2.17-py3.6.egg-info/SOURCES.txt exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser-2.17-py3.6.egg-info/dependency_links.txt exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser-2.17-py3.6.egg-info/top_level.txt exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__init__.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/_ast_gen.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/_build_tables.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/ast_transforms.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/c_ast.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/c_generator.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/c_lexer.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/c_parser.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/lextab.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/plyparser.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/__pycache__/yacctab.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/_ast_gen.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/_build_tables.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/_c_ast.cfg exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ast_transforms.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/c_ast.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/c_generator.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/c_lexer.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/c_parser.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/lextab.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/__init__.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/__pycache__/cpp.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/__pycache__/ctokens.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/__pycache__/lex.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/__pycache__/yacc.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/__pycache__/ygen.cpython-36.pyc exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/cpp.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/ctokens.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/lex.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/yacc.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/ply/ygen.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/plyparser.py exists in filesystem
python-pycparser: /usr/lib/python3.6/site-packages/pycparser/yacctab.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/_cffi_backend.cpython-36m-x86_64-linux-gnu.so exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__init__.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/api.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/backend_ctypes.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/cffi_opcode.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/commontypes.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/cparser.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/ffiplatform.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/lock.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/model.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/recompiler.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/setuptools_ext.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/vengine_cpy.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/vengine_gen.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/__pycache__/verifier.cpython-36.pyc exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/_cffi_include.h exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/_embedding.h exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/api.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/backend_ctypes.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/cffi_opcode.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/commontypes.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/cparser.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/ffiplatform.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/lock.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/model.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/parse_c_type.h exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/recompiler.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/setuptools_ext.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/vengine_cpy.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/vengine_gen.py exists in filesystem
python-cffi: /usr/lib/python3.6/site-packages/cffi/verifier.py exists in filesystem
python-hidapi: /usr/lib/python3.6/site-packages/hid.cpython-36m-x86_64-linux-gnu.so exists in filesystem
python-hidapi: /usr/lib/python3.6/site-packages/hidapi-0.7.99.post20-py3.6.egg-info/PKG-INFO exists in filesystem
python-hidapi: /usr/lib/python3.6/site-packages/hidapi-0.7.99.post20-py3.6.egg-info/SOURCES.txt exists in filesystem
python-hidapi: /usr/lib/python3.6/site-packages/hidapi-0.7.99.post20-py3.6.egg-info/dependency_links.txt exists in filesystem
python-hidapi: /usr/lib/python3.6/site-packages/hidapi-0.7.99.post20-py3.6.egg-info/requires.txt exists in filesystem
python-hidapi: /usr/lib/python3.6/site-packages/hidapi-0.7.99.post20-py3.6.egg-info/top_level.txt exists in filesystem
python-hidapi: /usr/lib/python3.6/site-packages/hidraw.cpython-36m-x86_64-linux-gnu.so exists in filesystem
Errors occurred, no packages were upgraded.
==> Restart building uchroma ? [y/N]
==> -----------------
```

**Comment by z3ntu** [comment]
That's because you have installed packages via pip manually. You should be fine `--force`ing the install of the packages.

**Comment by PipeItToDevNull** [comment]
@z3ntu 

```
┌─[✗]─[38]─[piper@ENCOMcorp]─[~/.bin/uchroma]
└╼ yaourt -S uchroma --force

==> Downloading uchroma PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
x uchroma.install
uchroma 1.0.1-1  (2017-03-19 20:07)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> n

==> uchroma dependencies:
 - python (already installed)
 - python-wrapt (package found)
 - python-traitlets (package found)
 - python-ruamel-yaml (package found)
 - python-scikit-image (building from AUR)
 - python-pydbus (building from AUR)
 - python-hsluv (building from AUR)
 - python-hidapi-cffi (building from AUR)
 - python-frozendict (package found)
 - python-colorlog (building from AUR)
 - python-argcomplete (building from AUR)
 - python-grapefruit (building from AUR)
 - python-cffi (package found)
 - hidapi (package found)
 - python-evdev (building from AUR)
 - python-pyudev (package found)
 - python-hidapi (package found)
 - python-gbulb (building from AUR)
 - python-colr (building from AUR)
 - python-dask (building from AUR)
 - cython (package found) [makedepend]
 - python-pytest-runner (package found) [makedepend]


==> Edit uchroma.install ? [Y/n] ("A" to abort)
==> -------------------------------------------
==> n

==> Continue building uchroma ? [Y/n]
==> ---------------------------------
==> y

==> Building and installing package
==> Install or build missing dependencies for uchroma:
[sudo] password for piper: 
resolving dependencies...
looking for conflicting packages...

Packages (15) python-decorator-4.0.11-1  python-ply-3.10-1  python-py-1.4.32-2  python-pycparser-2.17-2  python-pytest-3.0.6-1  cython-0.25.2-2  hidapi-0.8.0rc1-2  python-cffi-1.9.1-2  python-frozendict-1.2-2  python-hidapi-0.7.99.20-1
              python-pytest-runner-2.11.1-1  python-pyudev-0.21.0-2  python-ruamel-yaml-0.13.14-1  python-traitlets-4.3.2-1  python-wrapt-1.10.8-2

Total Installed Size:  16.84 MiB

:: Proceed with installation? [Y/n] y
(15/15) checking keys in keyring                                                                                                                        [----------------------------------------------------------------------------------------------] 100%
(15/15) checking package integrity                                                                                                                      [----------------------------------------------------------------------------------------------] 100%
(15/15) loading package files                                                                                                                           [----------------------------------------------------------------------------------------------] 100%
(15/15) checking for file conflicts                                                                                                                     [----------------------------------------------------------------------------------------------] 100%
(15/15) checking available disk space                                                                                                                   [----------------------------------------------------------------------------------------------] 100%
:: Processing package changes...
( 1/15) installing python-ply                                                                                                                           [----------------------------------------------------------------------------------------------] 100%
( 2/15) installing python-pycparser                                                                                                                     [----------------------------------------------------------------------------------------------] 100%
( 3/15) installing python-cffi                                                                                                                          [----------------------------------------------------------------------------------------------] 100%
( 4/15) installing python-wrapt                                                                                                                         [----------------------------------------------------------------------------------------------] 100%
( 5/15) installing cython                                                                                                                               [----------------------------------------------------------------------------------------------] 100%
( 6/15) installing python-ruamel-yaml                                                                                                                   [----------------------------------------------------------------------------------------------] 100%
( 7/15) installing python-py                                                                                                                            [----------------------------------------------------------------------------------------------] 100%
( 8/15) installing python-pytest                                                                                                                        [----------------------------------------------------------------------------------------------] 100%
( 9/15) installing python-pytest-runner                                                                                                                 [----------------------------------------------------------------------------------------------] 100%
(10/15) installing python-hidapi                                                                                                                        [----------------------------------------------------------------------------------------------] 100%
(11/15) installing python-frozendict                                                                                                                    [----------------------------------------------------------------------------------------------] 100%
(12/15) installing python-pyudev                                                                                                                        [----------------------------------------------------------------------------------------------] 100%
Optional dependencies for python-pyudev
    pyqt: PyQt integration
    python-gobject2: Glib integration
(13/15) installing hidapi                                                                                                                               [----------------------------------------------------------------------------------------------] 100%
(14/15) installing python-decorator                                                                                                                     [----------------------------------------------------------------------------------------------] 100%
(15/15) installing python-traitlets                                                                                                                     [----------------------------------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

==> Downloading python-argcomplete PKGBUILD from AUR...
x .SRCINFO
x PKGBUILD
flokli commented on 2014-04-04 22:06			 
argcomplete-0.7.1 is out

drichardson commented on 2014-12-05 17:33			 
Any chance global completion can be installed on the system with this package as described here? https://github.com/kislyuk/argcomplete#global-completion

mathben commented on 2016-10-28 22:54			 
Test error
======================================================================
ERROR: test_file_completion (__main__.TestArgcomplete)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test/test.py", line 252, in test_file_completion
os.makedirs(os.path.join("abcdef\u0436", "klm"))
File "/usr/lib/python3.5/os.py", line 229, in makedirs
if head and tail and not path.exists(head):
File "/usr/lib/python3.5/genericpath.py", line 19, in exists
os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0436' in position 6: ordinal not in range(128)

======================================================================
ERROR: test_filescompleter_filetype_integration (__main__.TestArgcomplete)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test/test.py", line 267, in test_filescompleter_filetype_integration
os.makedirs(os.path.join("abcdef\u0436", "klm"))
File "/usr/lib/python3.5/os.py", line 229, in makedirs
if head and tail and not path.exists(head):
File "/usr/lib/python3.5/genericpath.py", line 19, in exists
os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\u0436' in position 6: ordinal not in range(128)

======================================================================
ERROR: test_non_ascii (__main__.TestArgcomplete)
----------------------------------------------------------------------
Traceback (most recent call last):
File "test/test.py", line 354, in test_non_ascii
self.assertEqual(set(self.run_completer(make_parser(), cmd)),
File "test/test.py", line 76, in run_completer
exit_method=sys.exit, **kwargs)
File "/usr/lib/python3.5/unittest/case.py", line 727, in assertRaises
return context.handle('assertRaises', args, kwargs)
File "/usr/lib/python3.5/unittest/case.py", line 176, in handle
callable_obj(*args, **kwargs)
File "/tmp/yaourt-tmp-mathben/aur-python-argcomplete/src/argcomplete-1.6.0/argcomplete/__init__.py", line 209, in __call__
output_stream.write(ifs.join(completions).encode(sys_encoding))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 12-16: ordinal not in range(128)

anthraxx commented on 2016-10-28 23:46			 
can't reproduce: Ran 43 tests in 11.413s

Please make sure to build in a clean chroot like via "extra-x86_64-build" from devtools.

optlink commented on 2017-03-17 22:36			 
Any chance we could see this package updated?

python-argcomplete 1.6.0-1  (2016-10-21 15:35)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==> 

```

**Comment by cyanogen** [comment]
Working on packaging this up as a snap which at the very least eliminates the dependency hell.

**Comment by jramapuram** [comment]
+1 for the snap / flatpak ! I guess you might have to have access to some `/dev/USB*` devices?

**Comment by xsacha** [comment]
pacaur installed worked on Manjaro here.
Only issue I had wa python-sparse and parser-gblob check was failing so I had to modify the PkgBuild to remove tests.
