### ISSUE TITLE
uchromad service fails to start with Razer Blade Stealth (late 2016)

### ISSUE THREAD

**Issue by tschreibe** [cyanogen/uchroma#26]
Hi cyanogen,
I'm using the Kaby Lake Razer Blade Stealth on Arch, I managed to install the AUR package but I could not start the daemon.

Here's the trace:

uchromad -d
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/uchroma/util.py", line 346, in __call__
    return cls.__instance
AttributeError: type object 'UChromaDeviceManager' has no attribute '_Singleton__instance'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/uchromad", line 11, in <module>
    load_entry_point('uchroma==1.0.1', 'console_scripts', 'uchromad')()
  File "/usr/lib/python3.6/site-packages/uchroma/server/server.py", line 110, in run_server
    UChromaServer().run()
  File "/usr/lib/python3.6/site-packages/uchroma/server/server.py", line 59, in run
    self._run()
  File "/usr/lib/python3.6/site-packages/uchroma/server/server.py", line 65, in _run
    dm = UChromaDeviceManager()
  File "/usr/lib/python3.6/site-packages/uchroma/util.py", line 348, in __call__
    cls.__instance = super(Singleton, cls).__call__(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_manager.py", line 85, in __init__
    self.discover()
  File "/usr/lib/python3.6/site-packages/uchroma/server/device_manager.py", line 118, in discover
    if self._key_for_path(parent.sys_path) is not None:
AttributeError: 'NoneType' object has no attribute 'sys_path'

Did I do something wrong ? Maybe RBS is not supported ?

**Comment by tschreibe** [comment]
A reboot fixed it. Weird.
This works perfecly ! Great job and thanks, I can now remove razer-drivers packages.
