### ISSUE TITLE
uchroma -l returns empty

### ISSUE THREAD

**Issue by splushii** [cyanogen/uchroma#27]
Tried to install on Razer Blade Stealth (Kaby Lake) running openSUSE Tumbleweed. Could be same as https://github.com/cyanogen/uchroma/issues/13

`git clone https://github.com/cyanogen/uchroma.git`
I installed dependencies manually in order to successfully run 'sudo make install':
`sudo zypper in python-cffi`
`sudo pip install argcomplete cffi colorlog colr evdev frozendict gbulb grapefruit hidapi-cffi hsluv matplotlib numpy pydbus pyudev ruamel.yaml scikit-image scipy traitlets wrapt`
`sudo make install`

I noticed that uchromad seem to shut down:

```
Mar 30 21:07:52 linux-lbe3 dbus-daemon[1482]: Activating service name='org.chemlab.UChroma'
Mar 30 21:07:53 linux-lbe3 dbus-daemon[1482]: Successfully activated service 'org.chemlab.UChroma'
Mar 30 21:07:53 linux-lbe3 org.chemlab.UChroma[1482]:  uchroma.power/INFO     | Connected screensaver: org.freedesktop.ScreenSaver (':1.10',)
Mar 30 21:07:53 linux-lbe3 org.chemlab.UChroma[1482]:  uchroma.power/INFO     | Connected to org.freedesktop.login1 (':1.3',)
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]:  uchroma.server/INFO     | Shutting down
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]: Error in atexit._run_exitfuncs:
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]: Traceback (most recent call last):
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]:   File "/usr/lib64/python3.6/site-packages/uchroma/server/server.py", line 121, in exit
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]:     return_when=futures.ALL_COMPLETED))
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]:   File "/usr/lib/python3.6/site-packages/gbulb/glib_events.py", line 136, in run_until_complete
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]:     return future.result()
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]:   File "/usr/lib64/python3.6/asyncio/tasks.py", line 298, in wait
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]:     raise ValueError('Set of coroutines/Futures is empty.')
Mar 30 21:08:40 linux-lbe3 org.chemlab.UChroma[1482]: ValueError: Set of coroutines/Futures is empty.
```
When starting it again manually:
```
linux-lbe3:~> uchromad -d
 uchroma.devicemanager/DEBUG    | Udev monitor started                                              
 uchroma.power/INFO     | Connected screensaver: org.freedesktop.ScreenSaver (':1.10',)             
 uchroma.power/INFO     | Connected to org.freedesktop.login1 (':1.3',)
```
uchroma -l returns nothing:
```
linux-lbe3:~> uchroma -l
linux-lbe3:~>
```

lsusb output for reference:
```
Bus 001 Device 004: ID 1532:0220 Razer USA, Ltd 
Couldn't open device, some information will be missing
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x1532 Razer USA, Ltd
  idProduct          0x0220 
  bcdDevice            2.00
  iManufacturer           1 
  iProduct                2 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           84
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      61
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      1 Keyboard
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength     159
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      94
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
```

**Comment by jramapuram** [comment]
Same issue on Arch for me

**Comment by cyanogen** [comment]
Apparently something is different on the new Stealths.. I'll see if I can get my hands on one.

**Comment by jramapuram** [comment]
I'm running a GTX1060 2016 Skylake RB, not a stealth

**Comment by jtmkrueger** [comment]
I'm having the same issue on the new Pro 17"

**Comment by jacobcantele** [comment]
Yes, can confirm same issue on Razer Blade Pro 2017

**Comment by brad-decker** [comment]
Add another confirmation for razer blade pro 2017

**Comment by jacobcantele** [comment]
Any word on a fix for newer laptops?

**Comment by cyanogen** [comment]
Unfortunately not, I haven't been able to get my hands on any of the 2017 laptops and not for lack of trying.  If you're able to capture a packet trace in Windows while using Synapse, that could be very helpful.

**Comment by jramapuram** [comment]
This is also happening on my 2016 gtx1060 razer blade

**Comment by jtmkrueger** [comment]
@cyanogen I have dual booting setup on my 2017 razer blade pro. Is there any documentation regarding what you want as far as a packet trace? I'm more than happy to provide one, I'm just not sure how to go about getting it. I'll apologize in advance for my lack Windows knowledge.

**Comment by cyanogen** [comment]
There's an open pull request that brings in support for at least the new Blade. It may be as simple as adding the device to laptops.yaml.

**Comment by splushii** [comment]
I tested with the current version. The issue seems to be resolved for Razer Blade Stealth (Kaby Lake). Not sure about 2017 models so I am not closing this.

**Comment by keponk** [comment]
@cyanogen I've got a Razer Blade 2017. I attempted to copy the `laptop.yaml` file from the pull request into my installation via yaourt in Arch. No changes, after doing the change and rebooting the `uchroma -l` command still throws nothing.

If you give me instructions on how to collect packet trace data I'd be happy to produce it.

Thanks for the work on the project!

**Comment by xsacha** [comment]
Just like to add that I have the same issue, even after adding the pull request.

**Comment by SealedJoy** [comment]
same issue on blade stealth 13" 2020 (no devices show with uchroma -l)

**Comment by hyperb1iss** [comment]
this is fixed for 2.0 so many years later haha
