### ISSUE TITLE
Installing on Arch with yaourt have problem

### ISSUE THREAD

**Issue by ghost** [cyanogen/uchroma#31]
Hello thank you for this project,
I want to install this project from aur but get this error :) what we should do ?
```
error: failed to commit transaction (conflicting files)
python-wrapt: /usr/lib/python3.6/site-packages/wrapt-1.10.10-py3.6.egg-info exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/__init__.py exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/__pycache__/__init__.cpython-36.pyc exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/__pycache__/arguments.cpython-36.pyc exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/__pycache__/decorators.cpython-36.pyc exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/__pycache__/importer.cpython-36.pyc exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/__pycache__/wrappers.cpython-36.pyc exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/_wrappers.cpython-36m-x86_64-linux-gnu.so exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/arguments.py exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/decorators.py exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/importer.py exists in filesystem
python-wrapt: /usr/lib/python3.6/site-packages/wrapt/wrappers.py exists in filesystem
Errors occurred, no packages were upgraded.
```

**Comment by Mr-Virtuoso** [comment]
i finaly install with aur but when i am running uchroma -l i get this error

```
Traceback (most recent call last):
  File "/usr/bin/uchroma", line 11, in <module>
    load_entry_point('uchroma==1.0.1', 'console_scripts', 'uchroma')()
  File "/usr/lib/python3.6/site-packages/uchroma/client/client.py", line 702, in run_client
    UChromaTool().run()
  File "/usr/lib/python3.6/site-packages/uchroma/client/cmd.py", line 40, in __init__
    self._list_devices(self._args)
  File "/usr/lib/python3.6/site-packages/uchroma/client/cmd.py", line 57, in _list_devices
    for dev_path in self._client.get_device_paths():
  File "/usr/lib/python3.6/site-packages/uchroma/client/dbus_client.py", line 18, in get_device_paths
    dm = self._bus.get(SERVICE)
  File "/usr/lib/python3.6/site-packages/pydbus/proxy.py", line 47, in get
    0, timeout_to_glib(timeout), None)
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.chemlab.UChroma exited with status 1 (25)

```
what i shoul do for it ?

**Comment by ScottMorris** [comment]
Running into this as well.  Any luck getting it working?

Cheers
